// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190506.1

#ifndef WINRT_COROUTINE_H
#define WINRT_COROUTINE_H

#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.System.h"
#include "winrt/Windows.UI.Core.h"

#pragma message (__FILE__ "(" WINRT_IMPL_STRING(__LINE__) "): This header is deprecated and will be removed in a future update. Please directly include the namespace headers you need.")

#endif
