// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190506.1

#ifndef WINRT_Windows_Phone_PersonalInformation_Provisioning_0_H
#define WINRT_Windows_Phone_PersonalInformation_Provisioning_0_H
namespace winrt::Windows::Foundation
{
    struct IAsyncAction;
}
namespace winrt::Windows::Foundation::Collections
{
    template <typename K, typename V> struct IMapView;
    template <typename T> struct IVectorView;
}
namespace winrt::Windows::Phone::PersonalInformation
{
    struct ContactStore;
}
namespace winrt::Windows::Storage::Streams
{
    struct IInputStream;
}
namespace winrt::Windows::Phone::PersonalInformation::Provisioning
{
    struct IContactPartnerProvisioningManagerStatics;
    struct IContactPartnerProvisioningManagerStatics2;
    struct IMessagePartnerProvisioningManagerStatics;
    struct ContactPartnerProvisioningManager;
    struct MessagePartnerProvisioningManager;
}
namespace winrt::impl
{
    template <> struct category<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics>
    {
        using type = interface_category;
    };
    template <> struct category<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics2>
    {
        using type = interface_category;
    };
    template <> struct category<Windows::Phone::PersonalInformation::Provisioning::IMessagePartnerProvisioningManagerStatics>
    {
        using type = interface_category;
    };
    template <> struct category<Windows::Phone::PersonalInformation::Provisioning::ContactPartnerProvisioningManager>
    {
        using type = class_category;
    };
    template <> struct category<Windows::Phone::PersonalInformation::Provisioning::MessagePartnerProvisioningManager>
    {
        using type = class_category;
    };
    template <> struct name<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics>
    {
        static constexpr auto & value{ L"Windows.Phone.PersonalInformation.Provisioning.IContactPartnerProvisioningManagerStatics" };
    };
    template <> struct name<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics2>
    {
        static constexpr auto & value{ L"Windows.Phone.PersonalInformation.Provisioning.IContactPartnerProvisioningManagerStatics2" };
    };
    template <> struct name<Windows::Phone::PersonalInformation::Provisioning::IMessagePartnerProvisioningManagerStatics>
    {
        static constexpr auto & value{ L"Windows.Phone.PersonalInformation.Provisioning.IMessagePartnerProvisioningManagerStatics" };
    };
    template <> struct name<Windows::Phone::PersonalInformation::Provisioning::ContactPartnerProvisioningManager>
    {
        static constexpr auto & value{ L"Windows.Phone.PersonalInformation.Provisioning.ContactPartnerProvisioningManager" };
    };
    template <> struct name<Windows::Phone::PersonalInformation::Provisioning::MessagePartnerProvisioningManager>
    {
        static constexpr auto & value{ L"Windows.Phone.PersonalInformation.Provisioning.MessagePartnerProvisioningManager" };
    };
    template <> struct guid_storage<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics>
    {
        static constexpr guid value{ 0xC0D79A21,0x01AF,0x4FD3,{ 0x98,0xCD,0xB3,0xD6,0x56,0xDE,0x15,0xF4 } };
    };
    template <> struct guid_storage<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics2>
    {
        static constexpr guid value{ 0xC26155F7,0x55ED,0x475D,{ 0x93,0x34,0xC5,0xD4,0x84,0xC3,0x0F,0x1A } };
    };
    template <> struct guid_storage<Windows::Phone::PersonalInformation::Provisioning::IMessagePartnerProvisioningManagerStatics>
    {
        static constexpr guid value{ 0x8A1B0850,0x73C5,0x457C,{ 0xBC,0x59,0xED,0x7D,0x61,0x5C,0x05,0xA4 } };
    };
    template <> struct abi<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics>
    {
        struct WINRT_NOVTABLE type : inspectable_abi
        {
            virtual int32_t WINRT_CALL AssociateNetworkAccountAsync(void*, void*, void*, void**) noexcept = 0;
            virtual int32_t WINRT_CALL ImportVcardToSystemAsync(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics2>
    {
        struct WINRT_NOVTABLE type : inspectable_abi
        {
            virtual int32_t WINRT_CALL AssociateSocialNetworkAccountAsync(void*, void*, void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<Windows::Phone::PersonalInformation::Provisioning::IMessagePartnerProvisioningManagerStatics>
    {
        struct WINRT_NOVTABLE type : inspectable_abi
        {
            virtual int32_t WINRT_CALL ImportSmsToSystemAsync(bool, bool, void*, void*, void*, int64_t, void**) noexcept = 0;
            virtual int32_t WINRT_CALL ImportMmsToSystemAsync(bool, bool, void*, void*, void*, int64_t, void*, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Windows_Phone_PersonalInformation_Provisioning_IContactPartnerProvisioningManagerStatics
    {
        Windows::Foundation::IAsyncAction AssociateNetworkAccountAsync(Windows::Phone::PersonalInformation::ContactStore const& store, param::hstring const& networkName, param::hstring const& networkAccountId) const;
        Windows::Foundation::IAsyncAction ImportVcardToSystemAsync(Windows::Storage::Streams::IInputStream const& stream) const;
    };
    template <> struct consume<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics>
    {
        template <typename D> using type = consume_Windows_Phone_PersonalInformation_Provisioning_IContactPartnerProvisioningManagerStatics<D>;
    };
    template <typename D>
    struct consume_Windows_Phone_PersonalInformation_Provisioning_IContactPartnerProvisioningManagerStatics2
    {
        Windows::Foundation::IAsyncAction AssociateSocialNetworkAccountAsync(Windows::Phone::PersonalInformation::ContactStore const& store, param::hstring const& networkName, param::hstring const& networkAccountId) const;
    };
    template <> struct consume<Windows::Phone::PersonalInformation::Provisioning::IContactPartnerProvisioningManagerStatics2>
    {
        template <typename D> using type = consume_Windows_Phone_PersonalInformation_Provisioning_IContactPartnerProvisioningManagerStatics2<D>;
    };
    template <typename D>
    struct consume_Windows_Phone_PersonalInformation_Provisioning_IMessagePartnerProvisioningManagerStatics
    {
        Windows::Foundation::IAsyncAction ImportSmsToSystemAsync(bool incoming, bool read, param::hstring const& body, param::hstring const& sender, param::vector_view<hstring> const& recipients, Windows::Foundation::DateTime const& deliveryTime) const;
        Windows::Foundation::IAsyncAction ImportMmsToSystemAsync(bool incoming, bool read, param::hstring const& subject, param::hstring const& sender, param::vector_view<hstring> const& recipients, Windows::Foundation::DateTime const& deliveryTime, param::vector_view<Windows::Foundation::Collections::IMapView<hstring, Windows::Foundation::IInspectable>> const& attachments) const;
    };
    template <> struct consume<Windows::Phone::PersonalInformation::Provisioning::IMessagePartnerProvisioningManagerStatics>
    {
        template <typename D> using type = consume_Windows_Phone_PersonalInformation_Provisioning_IMessagePartnerProvisioningManagerStatics<D>;
    };
}
#endif
