// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190506.1

#ifndef WINRT_Windows_Perception_Spatial_1_H
#define WINRT_Windows_Perception_Spatial_1_H
#include "winrt/impl/Windows.Perception.Spatial.0.h"
namespace winrt::Windows::Perception::Spatial
{
    struct WINRT_EBO ISpatialAnchor :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchor>
    {
        ISpatialAnchor(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchor(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchor2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchor2>
    {
        ISpatialAnchor2(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchor2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorExportSufficiency :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorExportSufficiency>
    {
        ISpatialAnchorExportSufficiency(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorExportSufficiency(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorExporter :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorExporter>
    {
        ISpatialAnchorExporter(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorExporter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorExporterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorExporterStatics>
    {
        ISpatialAnchorExporterStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorExporterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorManagerStatics>
    {
        ISpatialAnchorManagerStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorRawCoordinateSystemAdjustedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorRawCoordinateSystemAdjustedEventArgs>
    {
        ISpatialAnchorRawCoordinateSystemAdjustedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorRawCoordinateSystemAdjustedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorStatics>
    {
        ISpatialAnchorStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorStore :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorStore>
    {
        ISpatialAnchorStore(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorStore(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialAnchorTransferManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialAnchorTransferManagerStatics>
    {
        ISpatialAnchorTransferManagerStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialAnchorTransferManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialBoundingVolume :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialBoundingVolume>
    {
        ISpatialBoundingVolume(std::nullptr_t = nullptr) noexcept {}
        ISpatialBoundingVolume(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialBoundingVolumeStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialBoundingVolumeStatics>
    {
        ISpatialBoundingVolumeStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialBoundingVolumeStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialCoordinateSystem :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialCoordinateSystem>
    {
        ISpatialCoordinateSystem(std::nullptr_t = nullptr) noexcept {}
        ISpatialCoordinateSystem(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntity :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntity>
    {
        ISpatialEntity(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntity(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityAddedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityAddedEventArgs>
    {
        ISpatialEntityAddedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityAddedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityFactory>
    {
        ISpatialEntityFactory(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityRemovedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityRemovedEventArgs>
    {
        ISpatialEntityRemovedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityRemovedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityStore :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityStore>
    {
        ISpatialEntityStore(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityStore(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityStoreStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityStoreStatics>
    {
        ISpatialEntityStoreStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityStoreStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityUpdatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityUpdatedEventArgs>
    {
        ISpatialEntityUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialEntityWatcher :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialEntityWatcher>
    {
        ISpatialEntityWatcher(std::nullptr_t = nullptr) noexcept {}
        ISpatialEntityWatcher(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialLocation :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialLocation>
    {
        ISpatialLocation(std::nullptr_t = nullptr) noexcept {}
        ISpatialLocation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialLocation2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialLocation2>
    {
        ISpatialLocation2(std::nullptr_t = nullptr) noexcept {}
        ISpatialLocation2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialLocator :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialLocator>
    {
        ISpatialLocator(std::nullptr_t = nullptr) noexcept {}
        ISpatialLocator(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialLocatorAttachedFrameOfReference :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialLocatorAttachedFrameOfReference>
    {
        ISpatialLocatorAttachedFrameOfReference(std::nullptr_t = nullptr) noexcept {}
        ISpatialLocatorAttachedFrameOfReference(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialLocatorPositionalTrackingDeactivatingEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialLocatorPositionalTrackingDeactivatingEventArgs>
    {
        ISpatialLocatorPositionalTrackingDeactivatingEventArgs(std::nullptr_t = nullptr) noexcept {}
        ISpatialLocatorPositionalTrackingDeactivatingEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialLocatorStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialLocatorStatics>
    {
        ISpatialLocatorStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialLocatorStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialStageFrameOfReference :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialStageFrameOfReference>
    {
        ISpatialStageFrameOfReference(std::nullptr_t = nullptr) noexcept {}
        ISpatialStageFrameOfReference(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialStageFrameOfReferenceStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialStageFrameOfReferenceStatics>
    {
        ISpatialStageFrameOfReferenceStatics(std::nullptr_t = nullptr) noexcept {}
        ISpatialStageFrameOfReferenceStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISpatialStationaryFrameOfReference :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISpatialStationaryFrameOfReference>
    {
        ISpatialStationaryFrameOfReference(std::nullptr_t = nullptr) noexcept {}
        ISpatialStationaryFrameOfReference(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
