// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190506.1

#ifndef WINRT_Windows_Phone_Management_Deployment_1_H
#define WINRT_Windows_Phone_Management_Deployment_1_H
#include "winrt/impl/Windows.Phone.Management.Deployment.0.h"
namespace winrt::Windows::Phone::Management::Deployment
{
    struct WINRT_EBO IEnterprise :
        Windows::Foundation::IInspectable,
        impl::consume_t<IEnterprise>
    {
        IEnterprise(std::nullptr_t = nullptr) noexcept {}
        IEnterprise(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IEnterpriseEnrollmentManager :
        Windows::Foundation::IInspectable,
        impl::consume_t<IEnterpriseEnrollmentManager>
    {
        IEnterpriseEnrollmentManager(std::nullptr_t = nullptr) noexcept {}
        IEnterpriseEnrollmentManager(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IEnterpriseEnrollmentResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IEnterpriseEnrollmentResult>
    {
        IEnterpriseEnrollmentResult(std::nullptr_t = nullptr) noexcept {}
        IEnterpriseEnrollmentResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IInstallationManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IInstallationManagerStatics>
    {
        IInstallationManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IInstallationManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IInstallationManagerStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IInstallationManagerStatics2>
    {
        IInstallationManagerStatics2(std::nullptr_t = nullptr) noexcept {}
        IInstallationManagerStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPackageInstallResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageInstallResult>
    {
        IPackageInstallResult(std::nullptr_t = nullptr) noexcept {}
        IPackageInstallResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPackageInstallResult2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageInstallResult2>
    {
        IPackageInstallResult2(std::nullptr_t = nullptr) noexcept {}
        IPackageInstallResult2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
