// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190506.1

#ifndef WINRT_Windows_ApplicationModel_Calls_1_H
#define WINRT_Windows_ApplicationModel_Calls_1_H
#include "winrt/impl/Windows.ApplicationModel.Calls.0.h"
namespace winrt::Windows::ApplicationModel::Calls
{
    struct WINRT_EBO ICallAnswerEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICallAnswerEventArgs>
    {
        ICallAnswerEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICallAnswerEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ICallRejectEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICallRejectEventArgs>
    {
        ICallRejectEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICallRejectEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ICallStateChangeEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICallStateChangeEventArgs>
    {
        ICallStateChangeEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICallStateChangeEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ILockScreenCallEndCallDeferral :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILockScreenCallEndCallDeferral>
    {
        ILockScreenCallEndCallDeferral(std::nullptr_t = nullptr) noexcept {}
        ILockScreenCallEndCallDeferral(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ILockScreenCallEndRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILockScreenCallEndRequestedEventArgs>
    {
        ILockScreenCallEndRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ILockScreenCallEndRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ILockScreenCallUI :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILockScreenCallUI>
    {
        ILockScreenCallUI(std::nullptr_t = nullptr) noexcept {}
        ILockScreenCallUI(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IMuteChangeEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMuteChangeEventArgs>
    {
        IMuteChangeEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMuteChangeEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallBlockingStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallBlockingStatics>
    {
        IPhoneCallBlockingStatics(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallBlockingStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryEntry :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryEntry>
    {
        IPhoneCallHistoryEntry(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryEntry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryEntryAddress :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryEntryAddress>
    {
        IPhoneCallHistoryEntryAddress(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryEntryAddress(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryEntryAddressFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryEntryAddressFactory>
    {
        IPhoneCallHistoryEntryAddressFactory(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryEntryAddressFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryEntryQueryOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryEntryQueryOptions>
    {
        IPhoneCallHistoryEntryQueryOptions(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryEntryQueryOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryEntryReader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryEntryReader>
    {
        IPhoneCallHistoryEntryReader(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryEntryReader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryManagerForUser :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryManagerForUser>
    {
        IPhoneCallHistoryManagerForUser(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryManagerForUser(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryManagerStatics>
    {
        IPhoneCallHistoryManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryManagerStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryManagerStatics2>
    {
        IPhoneCallHistoryManagerStatics2(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryManagerStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallHistoryStore :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallHistoryStore>
    {
        IPhoneCallHistoryStore(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallHistoryStore(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallManagerStatics>
    {
        IPhoneCallManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallManagerStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallManagerStatics2>
    {
        IPhoneCallManagerStatics2(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallManagerStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallStore :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallStore>
    {
        IPhoneCallStore(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallStore(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallVideoCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallVideoCapabilities>
    {
        IPhoneCallVideoCapabilities(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallVideoCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneCallVideoCapabilitiesManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneCallVideoCapabilitiesManagerStatics>
    {
        IPhoneCallVideoCapabilitiesManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IPhoneCallVideoCapabilitiesManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneDialOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneDialOptions>
    {
        IPhoneDialOptions(std::nullptr_t = nullptr) noexcept {}
        IPhoneDialOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLine :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLine>
    {
        IPhoneLine(std::nullptr_t = nullptr) noexcept {}
        IPhoneLine(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLine2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLine2>
    {
        IPhoneLine2(std::nullptr_t = nullptr) noexcept {}
        IPhoneLine2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineCellularDetails :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineCellularDetails>
    {
        IPhoneLineCellularDetails(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineCellularDetails(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineConfiguration :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineConfiguration>
    {
        IPhoneLineConfiguration(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineStatics>
    {
        IPhoneLineStatics(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineTransportDevice :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineTransportDevice>
    {
        IPhoneLineTransportDevice(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineTransportDevice(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineTransportDeviceStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineTransportDeviceStatics>
    {
        IPhoneLineTransportDeviceStatics(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineTransportDeviceStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineWatcher :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineWatcher>
    {
        IPhoneLineWatcher(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineWatcher(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneLineWatcherEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneLineWatcherEventArgs>
    {
        IPhoneLineWatcherEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPhoneLineWatcherEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPhoneVoicemail :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhoneVoicemail>
    {
        IPhoneVoicemail(std::nullptr_t = nullptr) noexcept {}
        IPhoneVoicemail(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVoipCallCoordinator :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipCallCoordinator>
    {
        IVoipCallCoordinator(std::nullptr_t = nullptr) noexcept {}
        IVoipCallCoordinator(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVoipCallCoordinator2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipCallCoordinator2>,
        impl::require<Windows::ApplicationModel::Calls::IVoipCallCoordinator2, Windows::ApplicationModel::Calls::IVoipCallCoordinator>
    {
        IVoipCallCoordinator2(std::nullptr_t = nullptr) noexcept {}
        IVoipCallCoordinator2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVoipCallCoordinator3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipCallCoordinator3>,
        impl::require<Windows::ApplicationModel::Calls::IVoipCallCoordinator3, Windows::ApplicationModel::Calls::IVoipCallCoordinator>
    {
        IVoipCallCoordinator3(std::nullptr_t = nullptr) noexcept {}
        IVoipCallCoordinator3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        using impl::consume_t<IVoipCallCoordinator3, IVoipCallCoordinator3>::RequestNewIncomingCall;
        using impl::consume_t<IVoipCallCoordinator3, Windows::ApplicationModel::Calls::IVoipCallCoordinator>::RequestNewIncomingCall;
    };
    struct WINRT_EBO IVoipCallCoordinator4 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipCallCoordinator4>,
        impl::require<Windows::ApplicationModel::Calls::IVoipCallCoordinator4, Windows::ApplicationModel::Calls::IVoipCallCoordinator>
    {
        IVoipCallCoordinator4(std::nullptr_t = nullptr) noexcept {}
        IVoipCallCoordinator4(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        using impl::consume_t<IVoipCallCoordinator4, IVoipCallCoordinator4>::ReserveCallResourcesAsync;
        using impl::consume_t<IVoipCallCoordinator4, Windows::ApplicationModel::Calls::IVoipCallCoordinator>::ReserveCallResourcesAsync;
    };
    struct WINRT_EBO IVoipCallCoordinatorStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipCallCoordinatorStatics>
    {
        IVoipCallCoordinatorStatics(std::nullptr_t = nullptr) noexcept {}
        IVoipCallCoordinatorStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVoipPhoneCall :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipPhoneCall>
    {
        IVoipPhoneCall(std::nullptr_t = nullptr) noexcept {}
        IVoipPhoneCall(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVoipPhoneCall2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipPhoneCall2>,
        impl::require<Windows::ApplicationModel::Calls::IVoipPhoneCall2, Windows::ApplicationModel::Calls::IVoipPhoneCall>
    {
        IVoipPhoneCall2(std::nullptr_t = nullptr) noexcept {}
        IVoipPhoneCall2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVoipPhoneCall3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVoipPhoneCall3>,
        impl::require<Windows::ApplicationModel::Calls::IVoipPhoneCall3, Windows::ApplicationModel::Calls::IVoipPhoneCall, Windows::ApplicationModel::Calls::IVoipPhoneCall2>
    {
        IVoipPhoneCall3(std::nullptr_t = nullptr) noexcept {}
        IVoipPhoneCall3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
