// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190506.1

#ifndef WINRT_Windows_Phone_ApplicationModel_1_H
#define WINRT_Windows_Phone_ApplicationModel_1_H
#include "winrt/impl/Windows.Phone.ApplicationModel.0.h"
namespace winrt::Windows::Phone::ApplicationModel
{
    struct WINRT_EBO IApplicationProfileStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IApplicationProfileStatics>
    {
        IApplicationProfileStatics(std::nullptr_t = nullptr) noexcept {}
        IApplicationProfileStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
